name: Publish QPM Package

permissions: write-all

env:
  qmodName: paper2_scotland2
  CARGO_TERM_COLOR: always
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Create Cargo LockFile
        run: cargo update

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  publish_qpm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Create ndkpath.txt
        run: |
          echo "$ANDROID_NDK_LATEST_HOME" > ${GITHUB_WORKSPACE}/ndkpath.txt
          cat ${GITHUB_WORKSPACE}/ndkpath.txt

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Create Cargo LockFile
        run: cargo update

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo ndk
        continue-on-error: true
        run: |
          cargo install cargo-ndk

      - name: Install Android toolchain
        continue-on-error: true
        run: |
          rustup target add aarch64-linux-android

  
      - name: Build
        run: |
          cd scotland2  
          cargo ndk --bindgen -o build -t arm64-v8a build --verbose


      # - name: Run tests
      #   run: cargo test --verbose

      - name: Get Tag Version
        id: get_tag_version
        run: |
          echo ${GITHUB_REF#refs/tags/}
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: QPM Rust Action
        uses: Fernthedev/qpm-action@v1
        with:
          #required
          # package_path: './scotland2'
          workflow_token: ${{secrets.GITHUB_TOKEN}}

          restore: true # will run restore on download
          cache: true #will cache dependencies

          publish: 'late'
          publish_token: ${{secrets.QPM_TOKEN}}

          version: ${{ steps.get_tag_version.outputs.VERSION }}
          tag: ${{ steps.get_tag_version.outputs.TAG }}

          # set to true if applicable, ASSUMES the file is already a release asset
          qpm_release_bin: true
          qpm_debug_bin: false

          # Name of qmod in release asset. Assumes exists, same as prior
          qpm_qmod: ${{env.qmodName}}.qmod

      - name: Make qmod paperlog
        run: |
          qpm qmod zip

      - name: Upload to Release
        id: upload_file_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./${{env.qmodName}}.qmod
            ./build/arm64-v8a/libpaper2_scotland2.so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}